### PR TITLE
Create structure for testing

### PR DESCRIPTION
**Pull request by MagoDelBlocco**
Added pom.xml dependency and file tree structure for the jUnit testing.

Includes two DELETEME files, since it didn't want to stage empty folders for push

### CODE REVIEW

**Comment by holounic** [comment]
Consider adding [Mockito](https://site.mockito.org/) dependency. It allows to use mocks, which could be very useful in our project because we are going to use database and external API. 
https://mvnrepository.com/artifact/org.mockito/mockito-core/3.5.2

**Review by holounic — CHANGES_REQUESTED** [review]
Consider adding [mockito](https://site.mockito.org/) dependency. It allows to use mocks, which could be very useful in our project because we are going to use database and external API. 
https://mvnrepository.com/artifact/org.mockito/mockito-core/3.5.2

**Comment by holounic** [comment]
It is very convenient to use other packeges for testing in Spring [a short article about testing in Spring](https://spring.io/guides/gs/testing-web/)
I would suggest to edit the current version of pom.xml and add the required dependencies to it instead of modifying the outdated version.

**Comment by MagoDelBlocco** [comment]
This PR got deprecated since the migration to Spring.

**Pull request closed without merging**
