### PR TITLE
Update BuildInfo to work with DatastoreTemplate

### PR DESCRIPTION
**Pull request by MagoDelBlocco**
DatastoreTemplate requires it's entities to have a default constructor, properties have a field name, and setters for all fields. This PR adds all those elements for BuildInfo.

### CODE REVIEW

**Comment by holounic** [comment]
Why the BuilderStatus enum has been removed?

**Comment by MagoDelBlocco** [comment]
> Why the BuilderStatus enum has been removed?

Was by mistake and forgot to amend before pushing. It will be solved in the merge.

**Review by holounic — APPROVED** [review]
LGTM! Please don't forget to return BuilderStatus when merging.

**Review by krasimir-google — APPROVED** [review]
LGTM

Thank you very much!

**Pull request merged**
