### PR TITLE
Update Main App Structure to Contain Core Components

### PR DESCRIPTION
**Pull request by samuelsogbesan**
This PR adds Header and BuildSnapshotContainer to the **App** component, which is the component rendered to the "root" div on the page.

This diagram below labels what the components represent:

image

### CODE REVIEW

**Review by MagoDelBlocco — APPROVED** [review]
I do not know if this applies to either Header or BuildSnapshotContainer, but I'll leave this here: [do not close void elements](https://google.github.io/styleguide/htmlcssguide.html#Document_Type) 
`  <Wrapper>
      <Header/>
      <BuildSnapshotContainer/>
    </Wrapper>`

**Comment by samuelsogbesan** [comment]
> I do not know if this applies to either Header or BuildSnapshotContainer, but I'll leave this here: [do not close void elements](https://google.github.io/styleguide/htmlcssguide.html#Document_Type)
> ` <Wrapper> <Header/> <BuildSnapshotContainer/> </Wrapper>`

@MagoDelBlocco These aren't traditional HTML elements. Instead, they are React Components that syntactically look like HTML elements with JSX's syntactic sugar. With React, it is required these components are self-closed, or else the syntax is incorrect.

**Comment by MagoDelBlocco** [comment]
> 
> @MagoDelBlocco These aren't traditional HTML elements. Instead, they are React Components that syntactically look like HTML elements with JSX's syntactic sugar. With React, it is required these components are self-closed, or else the syntax is incorrect.

LGTM then

**Review by Somae — APPROVED** [review]
LGTM

**Pull request merged**
